import { Character } from "~/data/Character"

export const getBasicTestCharacter = (): Character => {
    return {
        id: "",
        name: "Test Vampire",
        description: "A test vampire character",
        sire: "Test Sire",
        player: "",
        chronicle: "",
        sect: "",
        clan: "Brujah",
        predatorType: {
            name: "Sandman",
            pickedDiscipline: "auspex",
            pickedSpecialties: [
                {
                    skill: "medicine",
                    name: "Anesthetics",
                },
            ],
            pickedMeritsAndFlaws: [{ name: "Resources", level: 1, summary: "", type: "merit" }],
        },
        touchstones: [
            {
                name: "Test Touchstone",
                description: "A test touchstone",
                conviction: "Test conviction",
            },
        ],
        ambition: "Test ambition",
        desire: "Test desire",
        attributes: {
            strength: 3,
            dexterity: 2,
            stamina: 2,
            charisma: 2,
            manipulation: 1,
            composure: 2,
            intelligence: 2,
            wits: 2,
            resolve: 2,
        },
        skills: {
            athletics: 2,
            brawl: 1,
            craft: 0,
            drive: 1,
            firearms: 0,
            melee: 1,
            larceny: 0,
            stealth: 1,
            survival: 0,
            "animal ken": 0,
            etiquette: 0,
            insight: 1,
            intimidation: 2,
            leadership: 0,
            performance: 0,
            persuasion: 1,
            streetwise: 2,
            subterfuge: 0,
            academics: 1,
            awareness: 2,
            finance: 0,
            investigation: 1,
            medicine: 0,
            occult: 0,
            politics: 0,
            science: 0,
            technology: 1,
        },
        skillSpecialties: [
            {
                skill: "intimidation",
                name: "Direct Specialty",
            },
        ],
        availableDisciplineNames: ["potence", "blood sorcery"],
        disciplines: [
            {
                name: "Prowess",
                discipline: "potence",
                level: 1,
                summary: "Test prowess power",
                description: "A test prowess power description",
                dicePool: "Strength + Brawl",
                rouseChecks: 1,
                amalgamPrerequisites: [],
            },
            {
                name: "Corrosive Vitae",
                description: "",
                rouseChecks: 1,
                amalgamPrerequisites: [],
                summary: "make your blood corrosive to dead substances",
                dicePool: "",
                level: 1,
                discipline: "blood sorcery",
            },
        ],
        rituals: [
            {
                name: "Test Ritual",
                level: 1,
                summary: "A test ritual",
                rouseChecks: 1,
                dicePool: "Intelligence + Blood Sorcery",
                requiredTime: "1 hour",
                ingredients: "Blood of the subject",
            },
        ],
        bloodPotency: 1,
        generation: 13,
        maxHealth: 5,
        willpower: 4,
        experience: 15,
        humanity: 7,
        merits: [
            {
                name: "Direct Merit",
                level: 3,
                summary: "A direct merit",
                type: "merit",
            },
        ],
        flaws: [
            {
                name: "Direct Flaw",
                level: 2,
                summary: "A direct flaw",
                type: "flaw",
            },
        ],
        notes: "",
        ephemeral: {
            hunger: 0,
            superficialDamage: 0,
            aggravatedDamage: 0,
            superficialWillpowerDamage: 0,
            aggravatedWillpowerDamage: 0,
            humanityStains: 0,
            experienceSpent: 0,
        },
        version: 1,
    }
}
